create table JOB_TYPE (
   JOB_TYPE_ID INT    NOT NULL,
   JOB_TYPE VARCHAR NOT NULL,
   PRIMARY KEY (JOB_TYPE_ID)
);

create table JOBS (
   JOB_ID   VARCHAR(256)              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   EXEC_DTLS VARCHAR(20) NOT NULL,
   JOB_TYPE_ID INT NOT NULL,
   PRIMARY KEY (JOB_ID)
);

create TABLE JOB_STATUS_META (
    JOB_STATUS_META_ID INT NOT NULL,
    JOB_STATUS_TXT VARCHAR NOT NULL,
    PRIMARY KEY (JOB_STATUS_META_ID)
);

insert into JOB_STATUS_META(job_status_meta_id,job_status_txt) values(1,'SUCCESS');
insert into JOB_STATUS_META(job_status_meta_id,job_status_txt) values(2,'FAILED');

create table FREQ_META (
  FREQ_META_ID INT NOT NULL,
  FREQ_TYPE VARCHAR (20) NOT NULL,
  PRIMARY KEY (FREQ_META_ID)
);

insert into FREQ_META values(1,'DAILY');
insert into FREQ_META values(2,'MONTHLY');
insert into FREQ_META values(3,'YEARLY');
insert into FREQ_META values(4,'MINUTES');
insert into FREQ_META values(5,'SECONDS');



insert into JOB_TYPE values(1,'SCHEDULED');
insert into JOB_TYPE values(2,'ONDEMAND');



 create table JOB_EXECUTION_STATUS (
    JOB_EXECUTION_STATUS_ID VARCHAR(256) NOT NULL,
    JOB_ID VARCHAR(256) NOT NULL,
	JOB_STATUS_META_ID INT NOT NULL,
	START_TIME BIGINT NOT NULL,
	END_TIME BIGINT  NOT NULL,
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    PRIMARY KEY (JOB_EXECUTION_STATUS_ID),
    FOREIGN KEY (JOB_STATUS_META_ID) REFERENCES JOB_STATUS_META(JOB_STATUS_META_ID)
 );

create table EVNT(
   EVNT_ID   VARCHAR(256)   NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   PRIMARY KEY (EVNT_ID)
);


create TABLE EVNT_JOB (
   EVNT_JOB_ID VARCHAR(256) NOT NULL,
   EVNT_ID VARCHAR(256) NOT NULL,
   JOB_ID VARCHAR (256) NOT NULL
);

create table JOB_CONFIG (
   JOB_CONFIG_ID VARCHAR(256) NOT NULL,
   JOB_ID VARCHAR(256) NOT NULL,
   FREQ_META_ID INT  NULL,
   FREQ_VAL INT NULL
);

create table JOB_SCHEDULE (
   JOB_SCHEDULE_ID VARCHAR(256),
   JOB_ID VARCHAR(256),
   NEXT_RUN_TIME BIGINT
 );

